### PR TITLE
V2

### PR DESCRIPTION
**Pull request by developius**
Rewritten the whole app 😄

### CODE REVIEW

**Comment by popey456963** [comment]
Nice rewrite!  Although now it doesn't work on Windows :frowning_face:.  I'd better get moving to *nix quickly :slightly_smiling_face:.

**Comment by developius** [comment]
Oh great, what doesn't work @popey456963?

**Comment by popey456963** [comment]
@developius "Docker" (air quotes required...)

**Comment by developius** [comment]
Funny

**Pull request merged**
